FROM nginx

EXPOSE 80

COPY default.conf /etc/nginx/conf.d/default.conf
COPY MovieMarathon/index.html /usr/share/nginx/MovieMarathon/index.html
COPY MovieMarathon/bundle-prod.js /usr/share/nginx/MovieMarathon/bundle.js